### ISSUE TITLE
Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20

### ISSUE THREAD

**Issue by donfirst** [aws-actions/aws-cloudformation-github-deploy#125]
Hi Would  you be so kind and  have a look into that please
Best Regards,
Pete
Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: aws-actions/aws-cloudformation-github-deploy@v1. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.

**Comment by kddejong** [comment]
Newest release runs on v20.
