### ISSUE TITLE
Multiple capabilites causing an issue

### ISSUE THREAD

**Issue by sumeetsukhija** [aws-actions/aws-cloudformation-github-deploy#130]
Starting Feb 2nd 2024, The following error occurs on every build for multiple capabilities passed as below. 

```
 capabilities: CAPABILITY_NAMED_IAM, CAPABILITY_AUTO_EXPAND
```

Error: 1 validation error detected: Value '[CAPABILITY_NAMED_IAM,  CAPABILITY_AUTO_EXPAND]' at 'capabilities' failed to satisfy constraint: Member must satisfy constraint: [Member must satisfy enum value set: [CAPABILITY_AUTO_EXPAND, CAPABILITY_NAMED_IAM, CAPABILITY_IAM]]

**Comment by kddejong** [comment]
Found one possible issue but struggling a little with the error message and if my fix will fix the issue.

**Comment by kddejong** [comment]
Added in a test for multiple capabilities to match what you have.  If you have a chance take a look.

**Comment by kddejong** [comment]
I believe this is fixed and released.  We can re-open as needed.
