### ISSUE TITLE
Releasing new node version

### ISSUE THREAD

**Issue by MikitaSheleh** [aws-actions/aws-cloudformation-github-deploy#131]
Hello!
As described in [this](https://github.com/aws-actions/aws-cloudformation-github-deploy/issues/125) issue, Node version was updated, but when can we expect new release of this version?

Thanks in advance!
Best regards

**Comment by donfirst** [comment]
Hi, Can anyone make a release please?

**Comment by kddejong** [comment]
Released.  v1 has been updated and v1.3.0 has been released
