### ISSUE TITLE
Minor misleading in README / feature request

### ISSUE THREAD

**Issue by martinbiard** [aws-actions/aws-cloudformation-github-deploy#31]
The README states that:

> The action can be passed a CloudFormation Stack name and a template file. It will create the Stack if it does not exist, or create a Change Set to update the Stack.

However, it always executes the change-set. It is currently not possible to create the change-set to review it prior to executing it.

A great additional feature to this github action would be the support for the `--no-execute-changeset` aws-cli equivalent option.

**Comment by katallaxie** [comment]
@martinbiard please test the `master` branch.

**Comment by martinbiard** [comment]
Worked well, thank you.
