### ISSUE TITLE
Feature: Package templates and upload to Amazon S3 bucket

### ISSUE THREAD

**Issue by katallaxie** [aws-actions/aws-cloudformation-github-deploy#33]
This feature should implement the following behavior:

- Upload a template to an S3 bucket and replace URL in the template with the S3 URL
- Upload nested templates to an S3 bucket and replace URLs in the template with the S3 URL
- Use the referenced template in creating the stack or creating the changeset

Related issues:

https://github.com/aws-actions/aws-cloudformation-github-deploy/issues/32

**Comment by csd-oss** [comment]
Hello! I can't get it working, may you help? I don't see any input parameters for bucket and this does not work by default

**Comment by dhananjays** [comment]
Same here. Can you please suggest how this works @katallaxie? Thanks!
