### ISSUE TITLE
Mistake in documentation for parameter-overrides

### ISSUE THREAD

**Issue by MichalMiko** [aws-actions/aws-cloudformation-github-deploy#77]
Fix #61 introduced a mistake in the documentation stored in the `action.yml` 

Currently, the documentation states:

` (e.g. file://github.workspace/variables.json`

while it should say:

`(e.g. file://${{ github.workspace }}/variables.json`

This may not be an issue for experienced users but a simple copy paste from the documentation results in an error when running the action:
```
Error: File URL host must be "localhost" or empty on linux
```

Suggested fix:
Add the proper syntax as a comment in the `action.yml` file, for the `${{ github.workspace }}` not to be interpolated 
or
Add a section about using local parameter files the README file.

 I can work on both but I'd like some feedback first. @kddejong

**Comment by kddejong** [comment]
Turns out there is also an issue with how `${{ github.workspace }}` is used in `action.yml` in the description.  I think we will move most of that to the readme instead of the `action.yml`

**Comment by kddejong** [comment]
#91

**Comment by kddejong** [comment]
I think I got this fixed so let me know if we should do some more.
