### ISSUE TITLE
v1 tag should track latest v1.x.x release

### ISSUE THREAD

**Issue by tkrotoff** [aws-actions/aws-cloudformation-github-deploy#80]
v1 should point to v1.1.0 (latest release as of today) instead of v1.0.4

This is what others do: https://github.com/aws-actions/amazon-ecr-login/releases/tag/v1, https://github.com/aws-actions/configure-aws-credentials/releases/tag/v1

BTW v1 (v1.0.4) uses Node.js 12 (v1.1.0 uses Node.js 16) so all users gets these warnings:

> Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: aws-actions/aws-cloudformation-github-deploy@v1

> The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

Related issues:
- https://github.com/aws-actions/aws-cloudformation-github-deploy/issues/73
- https://github.com/aws-actions/aws-cloudformation-github-deploy/issues/79

**Comment by will-dcleite** [comment]
Hey guys, do we have a date when this will be updated?

**Comment by kddejong** [comment]
Agreed... release v1.2.0 today and I'll update this tag early next week.
