### ISSUE TITLE
All GitHub builds failing since latest release

### ISSUE THREAD

**Issue by mstephens** [aws-actions/aws-cloudformation-github-deploy#87]
Currently when running any action, the following error occurs:

<img width="884" alt="image" src="https://user-images.githubusercontent.com/893380/222585119-ee12a510-a56a-405e-874f-488568ea1e6b.png">

It's due to [this commit](https://github.com/aws-actions/aws-cloudformation-github-deploy/commit/87a972c53e8e3eba056d472b9579c2cd584be99a#diff-1243c5424efaaa19bd8e813c5e6f6da46316e63761421b3e5f5c8ced9a36e6b6R18).

Thank you

**Comment by huypd6946-cowell** [comment]
I'm facing the same issue. Please check!

**Comment by kddejong** [comment]
fixed #89

**Comment by kddejong** [comment]
v.1.2.0 release should have this fixed.  I'm going to update the v1 tag early next week so let me know if you still have any issues.
